name: Instrumentation unit tests
description: Run all the instrumentation unit test.

runs:
  using: composite

  steps:
    - name: Run instrumentation unit tests
      with:
        java-version: [8, 11, 17, 20, 21]
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} -Ptest${java-version} --info test