name: Instrumentation unit tests
description: Run all the instrumentation unit test.

runs:
  using: composite

  steps:
    - name: Run instrumentation unit tests
      id: run_tests
      shell: bash
      run: |
        for attempt in {1..4}; do
          echo "Attempt $attempt"
          ./gradlew ${GRADLE_OPTIONS} --info test && break || (echo "Run instrumentation unit tests attempt $attempt failed, waiting 5 seconds..." && sleep 5)
        done