name: Instrumentation unit tests
description: Run all the instrumentation unit test.

runs:
  using: composite

  steps:
    - name: Run instrumentation unit tests
      id: run_tests
      with:
        java-version:
      shell: bash
      run: |
        java_versions=("8" "11" "17" "20")
        for version in "${java_versions[@]}"; do
          for attempt in {1..4}; do
            echo "Attempt $attempt"
            ./gradlew ${GRADLE_OPTIONS} --info -Ptest${{version}} test && break || (echo "Run instrumentation unit tests attempt $attempt failed, waiting 5 seconds..." && sleep 5)
          done
        done