name: Instrumentation unit tests
description: Run all the instrumentation unit test.

runs:
  using: composite
  strategy:
    # max-parallel: 1 ## used to force sequential vs. concurrent
    fail-fast: false
    matrix:
      java-version: [ 8, 11, 17, 21 ]

  steps:
    - name: Run instrumentation unit tests on Java ${{ matrix.java-version }} attempt 1
      id: run_tests_1
      shell: bash
      continue-on-error: true
      run: ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ matrix.java-version }} --continue

    - name: Run instrumentation unit tests on Java ${{ matrix.java-version }} attempt 2
      id: run_tests_2
      shell: bash
      continue-on-error: true
      if: steps.run_tests_1.outcome == 'failure'
      run: ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ matrix.java-version }} --continue

    - name: Run instrumentation unit tests on Java ${{ matrix.java-version }} attempt 3
      id: run_tests_3
      shell: bash
      continue-on-error: true
      if: steps.run_tests_2.outcome == 'failure'
      run: ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ matrix.java-version }} --continue

    - name: Run instrumentation unit tests on Java ${{ matrix.java-version }} attempt 4
      id: run_tests_4
      shell: bash
      if: steps.run_tests_3.outcome == 'failure'
      run: ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ matrix.java-version }} --continue

