name: Instrumentation unit tests
description: Run all the instrumentation unit test.

runs:
  using: composite

  steps:
    - name: Run instrumentation unit tests
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} -Ptest8 --info test

    - name: Run instrumentation unit tests
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} -Ptest11 --info test

    - name: Run instrumentation unit tests
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} -Ptest17 --info test

    - name: Run instrumentation unit tests
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} -Ptest21 --info test

