name: Instrumentation unit tests
description: Run all the instrumentation unit test.
inputs:
  java-version:
    description: 'The JVM Version to use'
    required: true
    default: '8'
  csec-run-scala-unittest:
    description: 'Whether to run CSEC scala instrumentation unit tests'
    required: true
    default: 'false'

runs:
  using: composite

  steps:
    - name: Run scala instrumentation unit tests
      id: run_scala_unit_tests
      shell: bash
      if: (inputs.csec-run-scala-unittest == 'true' && inputs.java-version == '8')
      run: |
        ./gradlew $GRADLE_OPTIONS --info test -PincludeScala --continue

    - name: Run instrumentation unit tests on Java ${{ inputs.java-version }} attempt 1
      id: run_tests_1
      shell: bash
      continue-on-error: true
      run: |
        echo "Running attempt 1"
        ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ inputs.java-version }} --continue

    - name: Run instrumentation unit tests on Java ${{ inputs.java-version }} attempt 2
      id: run_tests_2
      shell: bash
      continue-on-error: true
      if: steps.run_tests_1.outcome == 'failure'
      run: |
        echo "Running attempt 2"
        ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ inputs.java-version }} --continue

    - name: Run instrumentation unit tests on Java ${{ inputs.java-version }} attempt 3
      id: run_tests_3
      shell: bash
      continue-on-error: true
      if: steps.run_tests_2.outcome == 'failure'
      run: |
        echo "Running attempt 3"
        ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ inputs.java-version }} --continue

    - name: Run instrumentation unit tests on Java ${{ inputs.java-version }} attempt 4
      id: run_tests_4
      shell: bash
      if: steps.run_tests_3.outcome == 'failure'
      run: |
        echo "Running attempt 4"
        ./gradlew ${GRADLE_OPTIONS} --info test -Ptest${{ inputs.java-version }} --continue