name: Publish CSEC Agent locally
description:  Builds the CSEC Agent and the Agent API. Publish to local maven repo.

runs:
  using: composite

  steps:
    - name: Publish CSEC agent API locally
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} :newrelic-security-api:publishToMavenLocal -PbuildNumber=${{ github.run_id }} -PcommitId=${{ github.sha }} --parallel

    - name: Publish CSEC agent locally
      shell: bash
      run: |
        ./gradlew ${GRADLE_OPTIONS} publishToMavenLocal -PbuildNumber=${{ github.run_id }} -PcommitId=${{ github.sha }} --parallel
