name: Verify Instrumentation
description: Run instrumentation verifier

runs:
  using: composite

  steps:
    - name: Run instrumentation unit tests
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} verifyInstrumentation --parallel
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}