name: Verify Instrumentation Single
description: Run instrumentation verifier on a single module
inputs:
  module-name:
    description: 'The module on which instrumentation verifier is to be run'
    required: true

runs:
  using: composite
  steps:
    - name: Run instrumentation unit tests
      shell: bash
      run: ./gradlew ${GRADLE_OPTIONS} :instrumentation:${{ inputs.module-name }}:verifyInstrumentation --parallel
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}