name: Dependency Submission

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph-include-projects: ':newrelic-security-(agent|api)'
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gralde.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"