name: Dependency Submission

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  dependency-submission:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph-exclude-projects: ':instrumentation'