# Workflow: Run Unit tests
#
# Trigger: This workflow runs on every merge to the main branch and on pull request.
name: Unit Tests
on:

  pull_request:
    branches: [ main ]

jobs:
  # this job reads the directories in csec-java-agent/instrumentation-security and creates a JSON with the list of the modules
  # this list is paginated and will be used in the verify-module job.
  build-agent:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]

    steps:
      - name: Checkout CSEC Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          apm-aws-access-key-id: ${{ secrets.APM_AWS_ACCESS_KEY_ID }}
          apm-aws-secret-access-key: ${{ secrets.APM_AWS_SECRET_ACCESS_KEY }}
          apm-aws-region: us-east-2

      - name: Publish CSEC to local
        uses: ./.github/actions/publish-csec-local

      - name: Run CSEC unit tests
        uses: ./.github/actions/unit-test
        with:
          csec-run-scala-unittest: true
          java-version: ${{ matrix.java-version }}