name: CSEC Single Instrumentation verification
on:
  workflow_call:
    inputs:
      module-name:
        description: 'Instrumentation module name to test'
        required: true
        type: string
        default: ''

  workflow_dispatch:
    inputs:
      module-name:
        description: 'Instrumentation module name to test'
        required: true
        default: ''

jobs:
  verify_instrumentation_single:
    name: Verify Instrumentation Single
    runs-on: ubuntu-20.04
    steps:
      - name: Print Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"

      - name: Checkout CSEC Java agent
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment-inst-verifier
        with:
          apm-aws-access-key-id: ${{ secrets.APM_AWS_ACCESS_KEY_ID }}
          apm-aws-secret-access-key: ${{ secrets.APM_AWS_SECRET_ACCESS_KEY }}
          apm-aws-region: us-east-2

      - name: Verify CSEC instrumentation
        uses: ./.github/actions/verify-instrumentation-single
        with:
          module-name: ${{ inputs.module-name }}